#!/bin/bash
cd /home/ishidin/phoenix || exit 0
grep -rn --binary-files=without-match \
  --include="*.js" --include="*.cjs" --include="*.mjs" --include="*.ts" \
  --include="*.sh" --include="*.py" --include="*.md" --include="*.html" \
  -E "exec[[:space:]]*\(" . 2>/dev/null \
  | grep -vE "node_modules|\.venv|\.git/|\.aider|/logs/|\.bak_|EXEC_CALLS_REPORT|COMMIT_CALLS_REPORT|\.exec_tmp|\.req_|\.tmp_|\.scan_|\.cf_scan|\.commit_scan|\.verify_|web/public" \
  > /tmp/all_exec.txt
echo "TOTAL: $(wc -l < /tmp/all_exec.txt)"
echo "=== by top dir ==="
cut -d/ -f2 /tmp/all_exec.txt | sort | uniq -c | sort -rn | head -30
echo "=== generated boxes/arena count ==="
grep -cE "^\./(boxes|arena)/" /tmp/all_exec.txt
echo "=== non-generated by file ==="
grep -vE "^\./(boxes|arena|skills_hub|terminal-bench|everos)/" /tmp/all_exec.txt | cut -d: -f1 | sort | uniq -c | sort -rn
echo "=== non-generated lines ==="
grep -vE "^\./(boxes|arena|skills_hub|terminal-bench|everos)/" /tmp/all_exec.txt
exit 0
